name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: python:3.8.13-slim

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: poetry install -v
      - name: Install python packages
        run: poetry install -v
      - name: Run Tests
        run: echo Test
      - name: Linter
        run: echo black
      - name: build container
        run: echo Build container
