name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.13
          architecture: x64

      - name: Install poetry
        run: pip install poetry
      - name: Install python packages
        run: poetry install -v

      - name: Run Tests
        run: echo Test
      - name: Linter
        run: echo black
      - name: build container
        run: echo Build container
