name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install python packages
        run: echo Hello from Octo Organization && ls
      - name: Run Tests
        run: echo Test
      - name: Linter
        run: echo black
      - name: build container
        run: echo Build container
