on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PR_GITHUB_TOKEN }}
          fetch-depth: 0
      - run: echo hello


