name: Pass Changes

on:
  push:
    branches: [ main ]

jobs:
  example1:
    runs-on: ubuntu-latest
    if: github.repository == 'r2dl/backend-framework'

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PR_GITHUB_TOKEN }}
        fetch-depth: 0
    - run: |
        git remote add example1 https://github.com/r2dl/backend-example1.git
        git push --set-upstream example1 main:base
        gh pr create --title "Base Code Updates" --body "Automatic Pull request from r2dl/backend-framework repo branch main" --base main --head base --repo r2dl/backend-example1 || echo "repo already created"
      env:
        GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}

  example2:
    runs-on: ubuntu-latest
    if: github.repository == 'r2dl/backend-framework'

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PR_GITHUB_TOKEN }}
        fetch-depth: 0
    - run: |
        git remote add example2 https://github.com/r2dl/backend-example2.git
        git push --set-upstream example2 main:base
        gh pr create --title "Base Code Updates" --body "Automatic Pull request from r2dl/backend-framework repo branch main" --base main --head base --repo r2dl/backend-example2 || echo "repo already created"
      env:
        GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
